Console.WriteLine("Введите значение b1: ");
double b1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите значение k1: ");
double k1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите значение b2: ");
double b2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите значение k2: ");
double k2 = Convert.ToDouble(Console.ReadLine());
double y;
double x;
x = (b1 - b2) / (k2 - k1);
y = k1 * x + b1;
Console.WriteLine($"({Math.Round(x, 2)}; {Math.Round(y, 2)})");